Nová sekce k architektonické dokumentaci pro ISVS nutné pro veřejnou …
NUKIB/bezpecnostni-doporuceni-open-source pull request #31
Opened 2022-01-18 10:53 UTC by michalradacz

U Open-source se dost často zapomíná na to, že psát cokoliv pro VŠ není jako si psát něco pro sebe či pro komerční sektor. Kromě bezpečnostních aspektů jsou tu i bezpečnostní povinnosti podle zákona o ISVS, alespoň jejich základ by bylo vhodné v tomto materiálu zohlednit a pomoci tak úřadům, kteří chtějí OS využívat i těm, kteří se na vývoji OS podílejí.

2022-01-19 08:34 UTC, MikkCZ requested changes
Pro gramatické a další chyby jsem dočetl jenom do konce A1. Kromě komentářů mě zde mrzí zavádění odkazů na konkrétní zákony a také formulace jak vykopírované z nějakého zákona nebo vyhlášky, čehož se dosavadnímu znění dokumentu dařilo vyhnout a což jsme pozitivně hodnotili v #33.

Abych ale nebyl jenom kritický, popis architektury softwaru, respektive požadavků na provoz má bezpečnostní význam. Např. pro provoz webové služby je dobré vědět, jaká je kapacita, požadavky pro její obsloužení a jak služba škáluje, protože aplikace, která nemá dostatek prostředků pro běh, se může dostávat do nečekaných stavů a to samozřejmě ovlivňuje i její bezpečnost.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Následující je platné vše vždy, pokud se jedná o informační systém veřejné správy, respektive nějakou komponentu či část, která je využívána jako ISVS a podléhá tedy Zákonu 365/2000 a povinnostem ply
> Následující je platné vše vždy

je docela krkolomná formulace.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí t
> pro podporu výkonu veřejné správy jsou regulovány

Chybí čárka před slovem _jsou_.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí t
> jsou součástí “informačních systémů veřejné správy” nebo “egulovaných informačních systémů! I části vytvořená jako otevřené dle tohoto doporučení

Tady se zřejmě popletla písmenka s vykřičníky a uvozovkami. A možná by to vlastně měly být dvě různé věty. Také by bylo fajn používat české uvozovky, pokud jsou potřeba.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí t
> Je tedy vhodné, aby již součástí dokumentace otevřeného kódu systému či jeho části, byly

Tady je zase druhá čárka před slovem _byly_ navíc.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +### A1: K programu nebo jeho části je v dokumentace uvedena základní architektura
_v dokumentaci_

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Jednou z cástídokumentace je také architektura. Architektura obsahuje standardizovaný a dále zpracovatelný popis základních částí řešení a jejich vazeb. Architektura se skládá z elementů a jejich pod
> Jednou z cástídokumentace

Chybí čárka.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Jednou z cástídokumentace je také architektura. Architektura obsahuje standardizovaný a dále zpracovatelný popis základních částí řešení a jejich vazeb. Architektura se skládá z elementů a jejich pod
Obecně bych neříkal, že součástí dokumentace je architektura. Architektura je skutečnost, jak je systém navržený. Vhodnější místo slova _architektura_ by bylo _dokumentace architektury_ nebo _popis architektury_.

2022-01-19 08:34 UTC, MikkCZ commented on bezpecnostni-doporuceni-open-source.md
> +Jednou z cástídokumentace je také architektura. Architektura obsahuje standardizovaný a dále zpracovatelný popis základních částí řešení a jejich vazeb. Architektura se skládá z elementů a jejich pod
> Je-lípou součástí

2x

2022-01-19 10:58 UTC, michalradacz commented
Já myslel, že teď se pouze navrhuje text. Takové ty korektury by se stejně měly dělat až na konci tedy až po  těch připomínkách u finálního dokumentu, takže jsem se tím prostě nezabýval.
S námitkou stran úřednické zákonné rétoriky souhlasím, zkusím to přepsat.


S pozdravem
Michal Rada

19. 1. 2022 v 9:34, Michal Stanke ***@***.***>:

﻿

@MikkCZ requested changes on this pull request.

Pro gramatické a další chyby jsem dočetl jenom do konce A1. Kromě komentářů mě zde mrzí zavádění odkazů na konkrétní zákony a také formulace jak vykopírované z nějakého zákona nebo vyhlášky, čehož se dosavadnímu znění dokumentu dařilo vyhnout a což jsme pozitivně hodnotili v #33<https://github.com/NUKIB/bezpecnostni-doporuceni-open-source/issues/33>.

________________________________

In bezpecnostni-doporuceni-open-source.md<https://github.com/NUKIB/bezpecnostni-doporuceni-open-source/pull/31#discussion_r787459185>:

> @@ -541,3 +539,121 @@ Pokud jsou v jedné transakci měněny nebo přidávány hodnoty do více datab

 ### D.6 Databázové schéma je komentováno
 Tabulky a sloupce jsou vhodně komentovány, aby byl jasný jejich význam a vazby na jiné tabulky.
+
+
+## Dokumentace a architektonické znalosti
+
+Následující je platné vše vždy, pokud se jedná o informační systém veřejné správy, respektive nějakou komponentu či část, která je využívána jako ISVS a podléhá tedy Zákonu 365/2000 a povinnostem plynoucích z Národní architektury. Nejedná-li se o část ISVS, i tak se autor snaží maximální počet následujících principů splnit.


Následující je platné vše vždy

je docela krkolomná formulace.

________________________________

In bezpecnostni-doporuceni-open-source.md<https://github.com/NUKIB/bezpecnostni-doporuceni-open-source/pull/31#discussion_r787459958>:

> @@ -541,3 +539,121 @@ Pokud jsou v jedné transakci měněny nebo přidávány hodnoty do více datab

 ### D.6 Databázové schéma je komentováno
 Tabulky a sloupce jsou vhodně komentovány, aby byl jasný jejich význam a vazby na jiné tabulky.
+
+
+## Dokumentace a architektonické znalosti
+
+Následující je platné vše vždy, pokud se jedná o informační systém veřejné správy, respektive nějakou komponentu či část, která je využívána jako ISVS a podléhá tedy Zákonu 365/2000 a povinnostem plynoucích z Národní architektury. Nejedná-li se o část ISVS, i tak se autor snaží maximální počet následujících principů splnit.
+
+Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí tedy, že pokud jsou součástí “informačních systémů veřejné správy” nebo “egulovaných informačních systémů! I části vytvořená jako otevřené dle tohoto doporučení, musí jejich rozvojem a implementací příslušný úřad plnit také povinnosti k ISVS a řízení informatiky (viz Zákon č. 365/2000 Sb., o informačních systémech veřejné správy a jeho prováděcí dokumenty). Je tedy vhodné, aby již součástí dokumentace otevřeného kódu systému či jeho části, byly také příslušné části architektonické dokumentace, aby se tak úřadům usnadnilo plnění povinností k ISVS.


pro podporu výkonu veřejné správy jsou regulovány

Chybí čárka před slovem jsou.

________________________________

In bezpecnostni-doporuceni-open-source.md<https://github.com/NUKIB/bezpecnostni-doporuceni-open-source/pull/31#discussion_r787461352>:

> @@ -541,3 +539,121 @@ Pokud jsou v jedné transakci měněny nebo přidávány hodnoty do více datab

 ### D.6 Databázové schéma je komentováno
 Tabulky a sloupce jsou vhodně komentovány, aby byl jasný jejich význam a vazby na jiné tabulky.
+
+
+## Dokumentace a architektonické znalosti
+
+Následující je platné vše vždy, pokud se jedná o informační systém veřejné správy, respektive nějakou komponentu či část, která je využívána jako ISVS a podléhá tedy Zákonu 365/2000 a povinnostem plynoucích z Národní architektury. Nejedná-li se o část ISVS, i tak se autor snaží maximální počet následujících principů splnit.
+
+Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí tedy, že pokud jsou součástí “informačních systémů veřejné správy” nebo “egulovaných informačních systémů! I části vytvořená jako otevřené dle tohoto doporučení, musí jejich rozvojem a implementací příslušný úřad plnit také povinnosti k ISVS a řízení informatiky (viz Zákon č. 365/2000 Sb., o informačních systémech veřejné správy a jeho prováděcí dokumenty). Je tedy vhodné, aby již součástí dokumentace otevřeného kódu systému či jeho části, byly také příslušné části architektonické dokumentace, aby se tak úřadům usnadnilo plnění povinností k ISVS.


jsou součástí “informačních systémů veřejné správy” nebo “egulovaných informačních systémů! I části vytvořená jako otevřené dle tohoto doporučení

Tady se zřejmě popletla písmenka s vykřičníky a uvozovkami. A možná by to vlastně měly být dvě různé věty. Také by bylo fajn používat české uvozovky, pokud jsou potřeba.

________________________________

In bezpecnostni-doporuceni-open-source.md<https://github.com/NUKIB/bezpecnostni-doporuceni-open-source/pull/31#discussion_r787462539>:

> @@ -541,3 +539,121 @@ Pokud jsou v jedné transakci měněny nebo přidávány hodnoty do více datab

 ### D.6 Databázové schéma je komentováno
 Tabulky a sloupce jsou vhodně komentovány, aby byl jasný jejich význam a vazby na jiné tabulky.
+
+
+## Dokumentace a architektonické znalosti
+
+Následující je platné vše vždy, pokud se jedná o informační systém veřejné správy, respektive nějakou komponentu či část, která je využívána jako ISVS a podléhá tedy Zákonu 365/2000 a povinnostem plynoucích z Národní architektury. Nejedná-li se o část ISVS, i tak se autor snaží maximální počet následujících principů splnit.
+
+Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí tedy, že pokud jsou součástí “informačních systémů veřejné správy” nebo “egulovaných informačních systémů! I části vytvořená jako otevřené dle tohoto doporučení, musí jejich rozvojem a implementací příslušný úřad plnit také povinnosti k ISVS a řízení informatiky (viz Zákon č. 365/2000 Sb., o informačních systémech veřejné správy a jeho prováděcí dokumenty). Je tedy vhodné, aby již součástí dokumentace otevřeného kódu systému či jeho části, byly také příslušné části architektonické dokumentace, aby se tak úřadům usnadnilo plnění povinností k ISVS.


Je tedy vhodné, aby již součástí dokumentace otevřeného kódu systému či jeho části, byly

Tady je zase druhá čárka před slovem byly navíc.

________________________________

In bezpecnostni-doporuceni-open-source.md<https://github.com/NUKIB/bezpecnostni-doporuceni-open-source/pull/31#discussion_r787462976>:

> @@ -541,3 +539,121 @@ Pokud jsou v jedné transakci měněny nebo přidávány hodnoty do více datab

 ### D.6 Databázové schéma je komentováno
 Tabulky a sloupce jsou vhodně komentovány, aby byl jasný jejich význam a vazby na jiné tabulky.
+
+
+## Dokumentace a architektonické znalosti
+
+Následující je platné vše vždy, pokud se jedná o informační systém veřejné správy, respektive nějakou komponentu či část, která je využívána jako ISVS a podléhá tedy Zákonu 365/2000 a povinnostem plynoucích z Národní architektury. Nejedná-li se o část ISVS, i tak se autor snaží maximální počet následujících principů splnit.
+
+Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí tedy, že pokud jsou součástí “informačních systémů veřejné správy” nebo “egulovaných informačních systémů! I části vytvořená jako otevřené dle tohoto doporučení, musí jejich rozvojem a implementací příslušný úřad plnit také povinnosti k ISVS a řízení informatiky (viz [...]

2022-01-19 11:22 UTC, R3gi commented
> Takové ty korektury by se stejně měly dělat až na konci tedy až po  těch připomínkách u finálního dokumentu, takže jsem se tím prostě nezabýval.

Dokument je vyvíjen iterativně. Není důvod začleňovat do hlavní větve očividně chybný kód… a spoléhat na to, že to možná někdy někdo opraví. Čím dříve se chyba odhalí, tím snadnější je její oprava. Proto se dělají code reviews :)

2022-01-19 17:33 UTC, paveljanik commented on bezpecnostni-doporuceni-open-source.md
> +Veškeré programové vybavení a programové potředky, jež veřejná správa využívá pro podporu výkonu veřejné správy jsou regulovány mimo jiné i legislativou k informačním systémům veřejné správy. Platí t
egulovaných -> regulovaných

2022-01-20 06:41 UTC, michalradacz commented
Ok, tenhle PR se asi může cancel. Navrhnu nové znění u sebe ve forgu a nejprve to sem pošlu k diskusím a opravám, PR až potom.

2022-01-20 07:18 UTC, closed without merging